CREATE TABLE BAMEIORIGIN
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    KettoNum char(10),
    Bamei char(36),
    Origin char(64),
    PRIMARY KEY (KettoNum)
);

CREATE TABLE BANUSI
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    BanusiCode char(6),
    BanusiName char(64),
    BanusiName_Co char(64),
    BanusiNameKana char(50),
    BanusiNameEng char(100),
    Fukusyoku char(60),
    H_SetYear char(4),
    H_HonSyokinTotal char(10),
    H_FukaSyokin char(10),
    H_ChakuKaisu1 char(6),
    H_ChakuKaisu2 char(6),
    H_ChakuKaisu3 char(6),
    H_ChakuKaisu4 char(6),
    H_ChakuKaisu5 char(6),
    H_ChakuKaisu6 char(6),
    R_SetYear char(4),
    R_HonSyokinTotal char(10),
    R_FukaSyokin char(10),
    R_ChakuKaisu1 char(6),
    R_ChakuKaisu2 char(6),
    R_ChakuKaisu3 char(6),
    R_ChakuKaisu4 char(6),
    R_ChakuKaisu5 char(6),
    R_ChakuKaisu6 char(6),
    PRIMARY KEY (BanusiCode)
);

CREATE TABLE BATAIJYU
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    HappyoTime char(8),
    Umaban1 char(2),
    Bamei1 char(36),
    BaTaijyu1 char(3),
    ZogenFugo1 char(1),
    ZogenSa1 char(3),
    Umaban2 char(2),
    Bamei2 char(36),
    BaTaijyu2 char(3),
    ZogenFugo2 char(1),
    ZogenSa2 char(3),
    Umaban3 char(2),
    Bamei3 char(36),
    BaTaijyu3 char(3),
    ZogenFugo3 char(1),
    ZogenSa3 char(3),
    Umaban4 char(2),
    Bamei4 char(36),
    BaTaijyu4 char(3),
    ZogenFugo4 char(1),
    ZogenSa4 char(3),
    Umaban5 char(2),
    Bamei5 char(36),
    BaTaijyu5 char(3),
    ZogenFugo5 char(1),
    ZogenSa5 char(3),
    Umaban6 char(2),
    Bamei6 char(36),
    BaTaijyu6 char(3),
    ZogenFugo6 char(1),
    ZogenSa6 char(3),
    Umaban7 char(2),
    Bamei7 char(36),
    BaTaijyu7 char(3),
    ZogenFugo7 char(1),
    ZogenSa7 char(3),
    Umaban8 char(2),
    Bamei8 char(36),
    BaTaijyu8 char(3),
    ZogenFugo8 char(1),
    ZogenSa8 char(3),
    Umaban9 char(2),
    Bamei9 char(36),
    BaTaijyu9 char(3),
    ZogenFugo9 char(1),
    ZogenSa9 char(3),
    Umaban10 char(2),
    Bamei10 char(36),
    BaTaijyu10 char(3),
    ZogenFugo10 char(1),
    ZogenSa10 char(3),
    Umaban11 char(2),
    Bamei11 char(36),
    BaTaijyu11 char(3),
    ZogenFugo11 char(1),
    ZogenSa11 char(3),
    Umaban12 char(2),
    Bamei12 char(36),
    BaTaijyu12 char(3),
    ZogenFugo12 char(1),
    ZogenSa12 char(3),
    Umaban13 char(2),
    Bamei13 char(36),
    BaTaijyu13 char(3),
    ZogenFugo13 char(1),
    ZogenSa13 char(3),
    Umaban14 char(2),
    Bamei14 char(36),
    BaTaijyu14 char(3),
    ZogenFugo14 char(1),
    ZogenSa14 char(3),
    Umaban15 char(2),
    Bamei15 char(36),
    BaTaijyu15 char(3),
    ZogenFugo15 char(1),
    ZogenSa15 char(3),
    Umaban16 char(2),
    Bamei16 char(36),
    BaTaijyu16 char(3),
    ZogenFugo16 char(1),
    ZogenSa16 char(3),
    Umaban17 char(2),
    Bamei17 char(36),
    BaTaijyu17 char(3),
    ZogenFugo17 char(1),
    ZogenSa17 char(3),
    Umaban18 char(2),
    Bamei18 char(36),
    BaTaijyu18 char(3),
    ZogenFugo18 char(1),
    ZogenSa18 char(3),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
);

CREATE TABLE CHOKYO
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    ChokyosiCode char(5),
    DelKubun char(1),
    IssueDate char(8),
    DelDate char(8),
    BirthDate char(8),
    ChokyosiName char(34),
    ChokyosiNameKana char(30),
    ChokyosiRyakusyo char(8),
    ChokyosiNameEng char(80),
    SexCD char(1),
    TozaiCD char(1),
    Syotai char(20),
    SaikinJyusyo1SaikinJyusyoid char(16),
    SaikinJyusyo1Hondai char(60),
    SaikinJyusyo1Ryakusyo10 char(20),
    SaikinJyusyo1Ryakusyo6 char(12),
    SaikinJyusyo1Ryakusyo3 char(6),
    SaikinJyusyo1GradeCD char(1),
    SaikinJyusyo1SyussoTosu char(2),
    SaikinJyusyo1KettoNum char(10),
    SaikinJyusyo1Bamei char(36),
    SaikinJyusyo2SaikinJyusyoid char(16),
    SaikinJyusyo2Hondai char(60),
    SaikinJyusyo2Ryakusyo10 char(20),
    SaikinJyusyo2Ryakusyo6 char(12),
    SaikinJyusyo2Ryakusyo3 char(6),
    SaikinJyusyo2GradeCD char(1),
    SaikinJyusyo2SyussoTosu char(2),
    SaikinJyusyo2KettoNum char(10),
    SaikinJyusyo2Bamei char(36),
    SaikinJyusyo3SaikinJyusyoid char(16),
    SaikinJyusyo3Hondai char(60),
    SaikinJyusyo3Ryakusyo10 char(20),
    SaikinJyusyo3Ryakusyo6 char(12),
    SaikinJyusyo3Ryakusyo3 char(6),
    SaikinJyusyo3GradeCD char(1),
    SaikinJyusyo3SyussoTosu char(2),
    SaikinJyusyo3KettoNum char(10),
    SaikinJyusyo3Bamei char(36),
    PRIMARY KEY (ChokyosiCode)
);

CREATE TABLE CHOKYO_SEISEKI
(
    MakeDate char(8),
    ChokyosiCode char(5),
    Num char(1),
    SetYear char(4),
    HonSyokinHeichi char(10),
    HonSyokinSyogai char(10),
    FukaSyokinHeichi char(10),
    FukaSyokinSyogai char(10),
    HeichiChakukaisu1 char(6),
    HeichiChakukaisu2 char(6),
    HeichiChakukaisu3 char(6),
    HeichiChakukaisu4 char(6),
    HeichiChakukaisu5 char(6),
    HeichiChakukaisu6 char(6),
    SyogaiChakukaisu1 char(6),
    SyogaiChakukaisu2 char(6),
    SyogaiChakukaisu3 char(6),
    SyogaiChakukaisu4 char(6),
    SyogaiChakukaisu5 char(6),
    SyogaiChakukaisu6 char(6),
    Jyo1Chakukaisu1 char(6),
    Jyo1Chakukaisu2 char(6),
    Jyo1Chakukaisu3 char(6),
    Jyo1Chakukaisu4 char(6),
    Jyo1Chakukaisu5 char(6),
    Jyo1Chakukaisu6 char(6),
    Jyo2Chakukaisu1 char(6),
    Jyo2Chakukaisu2 char(6),
    Jyo2Chakukaisu3 char(6),
    Jyo2Chakukaisu4 char(6),
    Jyo2Chakukaisu5 char(6),
    Jyo2Chakukaisu6 char(6),
    Jyo3Chakukaisu1 char(6),
    Jyo3Chakukaisu2 char(6),
    Jyo3Chakukaisu3 char(6),
    Jyo3Chakukaisu4 char(6),
    Jyo3Chakukaisu5 char(6),
    Jyo3Chakukaisu6 char(6),
    Jyo4Chakukaisu1 char(6),
    Jyo4Chakukaisu2 char(6),
    Jyo4Chakukaisu3 char(6),
    Jyo4Chakukaisu4 char(6),
    Jyo4Chakukaisu5 char(6),
    Jyo4Chakukaisu6 char(6),
    Jyo5Chakukaisu1 char(6),
    Jyo5Chakukaisu2 char(6),
    Jyo5Chakukaisu3 char(6),
    Jyo5Chakukaisu4 char(6),
    Jyo5Chakukaisu5 char(6),
    Jyo5Chakukaisu6 char(6),
    Jyo6Chakukaisu1 char(6),
    Jyo6Chakukaisu2 char(6),
    Jyo6Chakukaisu3 char(6),
    Jyo6Chakukaisu4 char(6),
    Jyo6Chakukaisu5 char(6),
    Jyo6Chakukaisu6 char(6),
    Jyo7Chakukaisu1 char(6),
    Jyo7Chakukaisu2 char(6),
    Jyo7Chakukaisu3 char(6),
    Jyo7Chakukaisu4 char(6),
    Jyo7Chakukaisu5 char(6),
    Jyo7Chakukaisu6 char(6),
    Jyo8Chakukaisu1 char(6),
    Jyo8Chakukaisu2 char(6),
    Jyo8Chakukaisu3 char(6),
    Jyo8Chakukaisu4 char(6),
    Jyo8Chakukaisu5 char(6),
    Jyo8Chakukaisu6 char(6),
    Jyo9Chakukaisu1 char(6),
    Jyo9Chakukaisu2 char(6),
    Jyo9Chakukaisu3 char(6),
    Jyo9Chakukaisu4 char(6),
    Jyo9Chakukaisu5 char(6),
    Jyo9Chakukaisu6 char(6),
    Jyo10Chakukaisu1 char(6),
    Jyo10Chakukaisu2 char(6),
    Jyo10Chakukaisu3 char(6),
    Jyo10Chakukaisu4 char(6),
    Jyo10Chakukaisu5 char(6),
    Jyo10Chakukaisu6 char(6),
    Jyo11Chakukaisu1 char(6),
    Jyo11Chakukaisu2 char(6),
    Jyo11Chakukaisu3 char(6),
    Jyo11Chakukaisu4 char(6),
    Jyo11Chakukaisu5 char(6),
    Jyo11Chakukaisu6 char(6),
    Jyo12Chakukaisu1 char(6),
    Jyo12Chakukaisu2 char(6),
    Jyo12Chakukaisu3 char(6),
    Jyo12Chakukaisu4 char(6),
    Jyo12Chakukaisu5 char(6),
    Jyo12Chakukaisu6 char(6),
    Jyo13Chakukaisu1 char(6),
    Jyo13Chakukaisu2 char(6),
    Jyo13Chakukaisu3 char(6),
    Jyo13Chakukaisu4 char(6),
    Jyo13Chakukaisu5 char(6),
    Jyo13Chakukaisu6 char(6),
    Jyo14Chakukaisu1 char(6),
    Jyo14Chakukaisu2 char(6),
    Jyo14Chakukaisu3 char(6),
    Jyo14Chakukaisu4 char(6),
    Jyo14Chakukaisu5 char(6),
    Jyo14Chakukaisu6 char(6),
    Jyo15Chakukaisu1 char(6),
    Jyo15Chakukaisu2 char(6),
    Jyo15Chakukaisu3 char(6),
    Jyo15Chakukaisu4 char(6),
    Jyo15Chakukaisu5 char(6),
    Jyo15Chakukaisu6 char(6),
    Jyo16Chakukaisu1 char(6),
    Jyo16Chakukaisu2 char(6),
    Jyo16Chakukaisu3 char(6),
    Jyo16Chakukaisu4 char(6),
    Jyo16Chakukaisu5 char(6),
    Jyo16Chakukaisu6 char(6),
    Jyo17Chakukaisu1 char(6),
    Jyo17Chakukaisu2 char(6),
    Jyo17Chakukaisu3 char(6),
    Jyo17Chakukaisu4 char(6),
    Jyo17Chakukaisu5 char(6),
    Jyo17Chakukaisu6 char(6),
    Jyo18Chakukaisu1 char(6),
    Jyo18Chakukaisu2 char(6),
    Jyo18Chakukaisu3 char(6),
    Jyo18Chakukaisu4 char(6),
    Jyo18Chakukaisu5 char(6),
    Jyo18Chakukaisu6 char(6),
    Jyo19Chakukaisu1 char(6),
    Jyo19Chakukaisu2 char(6),
    Jyo19Chakukaisu3 char(6),
    Jyo19Chakukaisu4 char(6),
    Jyo19Chakukaisu5 char(6),
    Jyo19Chakukaisu6 char(6),
    Jyo20Chakukaisu1 char(6),
    Jyo20Chakukaisu2 char(6),
    Jyo20Chakukaisu3 char(6),
    Jyo20Chakukaisu4 char(6),
    Jyo20Chakukaisu5 char(6),
    Jyo20Chakukaisu6 char(6),
    Kyori1Chakukaisu1 char(6),
    Kyori1Chakukaisu2 char(6),
    Kyori1Chakukaisu3 char(6),
    Kyori1Chakukaisu4 char(6),
    Kyori1Chakukaisu5 char(6),
    Kyori1Chakukaisu6 char(6),
    Kyori2Chakukaisu1 char(6),
    Kyori2Chakukaisu2 char(6),
    Kyori2Chakukaisu3 char(6),
    Kyori2Chakukaisu4 char(6),
    Kyori2Chakukaisu5 char(6),
    Kyori2Chakukaisu6 char(6),
    Kyori3Chakukaisu1 char(6),
    Kyori3Chakukaisu2 char(6),
    Kyori3Chakukaisu3 char(6),
    Kyori3Chakukaisu4 char(6),
    Kyori3Chakukaisu5 char(6),
    Kyori3Chakukaisu6 char(6),
    Kyori4Chakukaisu1 char(6),
    Kyori4Chakukaisu2 char(6),
    Kyori4Chakukaisu3 char(6),
    Kyori4Chakukaisu4 char(6),
    Kyori4Chakukaisu5 char(6),
    Kyori4Chakukaisu6 char(6),
    Kyori5Chakukaisu1 char(6),
    Kyori5Chakukaisu2 char(6),
    Kyori5Chakukaisu3 char(6),
    Kyori5Chakukaisu4 char(6),
    Kyori5Chakukaisu5 char(6),
    Kyori5Chakukaisu6 char(6),
    Kyori6Chakukaisu1 char(6),
    Kyori6Chakukaisu2 char(6),
    Kyori6Chakukaisu3 char(6),
    Kyori6Chakukaisu4 char(6),
    Kyori6Chakukaisu5 char(6),
    Kyori6Chakukaisu6 char(6),
    PRIMARY KEY (ChokyosiCode, Num)
);

CREATE TABLE COURSE
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    JyoCD char(2),
    Kyori char(4),
    TrackCD char(2),
    KaishuDate char(8),
    CourseEx text,
    PRIMARY KEY (JyoCD, Kyori, TrackCD, KaishuDate)
);

CREATE TABLE COURSE_CHANGE
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    HappyoTime char(8),
    AtoKyori char(4),
    AtoTruckCD char(2),
    MaeKyori char(4),
    MaeTruckCD char(2),
    JiyuCD char(1),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, HappyoTime)
);

CREATE TABLE HANRO
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    TresenKubun char(1),
    ChokyoDate char(8),
    ChokyoTime char(4),
    KettoNum char(10),
    HaronTime4 char(4),
    LapTime4 char(3),
    HaronTime3 char(4),
    LapTime3 char(3),
    HaronTime2 char(4),
    LapTime2 char(3),
    LapTime1 char(3),
    PRIMARY KEY (TresenKubun, ChokyoDate, ChokyoTime, KettoNum)
);

CREATE TABLE HANSYOKU
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    HansyokuNum char(8),
    reserved char(8),
    KettoNum char(10),
    DelKubun char(1),
    Bamei char(36),
    BameiKana char(40),
    BameiEng char(80),
    BirthYear char(4),
    SexCD char(1),
    HinsyuCD char(1),
    KeiroCD char(2),
    HansyokuMochiKubun char(1),
    ImportYear char(4),
    SanchiName char(20),
    HansyokuFNum char(8),
    HansyokuMNum char(8),
    PRIMARY KEY (HansyokuNum)
);

CREATE TABLE HARAI
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    TorokuTosu char(2),
    SyussoTosu char(2),
    FuseirituFlag1 char(1),
    FuseirituFlag2 char(1),
    FuseirituFlag3 char(1),
    FuseirituFlag4 char(1),
    FuseirituFlag5 char(1),
    FuseirituFlag6 char(1),
    FuseirituFlag7 char(1),
    FuseirituFlag8 char(1),
    FuseirituFlag9 char(1),
    TokubaraiFlag1 char(1),
    TokubaraiFlag2 char(1),
    TokubaraiFlag3 char(1),
    TokubaraiFlag4 char(1),
    TokubaraiFlag5 char(1),
    TokubaraiFlag6 char(1),
    TokubaraiFlag7 char(1),
    TokubaraiFlag8 char(1),
    TokubaraiFlag9 char(1),
    HenkanFlag1 char(1),
    HenkanFlag2 char(1),
    HenkanFlag3 char(1),
    HenkanFlag4 char(1),
    HenkanFlag5 char(1),
    HenkanFlag6 char(1),
    HenkanFlag7 char(1),
    HenkanFlag8 char(1),
    HenkanFlag9 char(1),
    HenkanUma1 char(1),
    HenkanUma2 char(1),
    HenkanUma3 char(1),
    HenkanUma4 char(1),
    HenkanUma5 char(1),
    HenkanUma6 char(1),
    HenkanUma7 char(1),
    HenkanUma8 char(1),
    HenkanUma9 char(1),
    HenkanUma10 char(1),
    HenkanUma11 char(1),
    HenkanUma12 char(1),
    HenkanUma13 char(1),
    HenkanUma14 char(1),
    HenkanUma15 char(1),
    HenkanUma16 char(1),
    HenkanUma17 char(1),
    HenkanUma18 char(1),
    HenkanUma19 char(1),
    HenkanUma20 char(1),
    HenkanUma21 char(1),
    HenkanUma22 char(1),
    HenkanUma23 char(1),
    HenkanUma24 char(1),
    HenkanUma25 char(1),
    HenkanUma26 char(1),
    HenkanUma27 char(1),
    HenkanUma28 char(1),
    HenkanWaku1 char(1),
    HenkanWaku2 char(1),
    HenkanWaku3 char(1),
    HenkanWaku4 char(1),
    HenkanWaku5 char(1),
    HenkanWaku6 char(1),
    HenkanWaku7 char(1),
    HenkanWaku8 char(1),
    HenkanDoWaku1 char(1),
    HenkanDoWaku2 char(1),
    HenkanDoWaku3 char(1),
    HenkanDoWaku4 char(1),
    HenkanDoWaku5 char(1),
    HenkanDoWaku6 char(1),
    HenkanDoWaku7 char(1),
    HenkanDoWaku8 char(1),
    PayTansyoUmaban1 char(2),
    PayTansyoPay1 char(9),
    PayTansyoNinki1 char(2),
    PayTansyoUmaban2 char(2),
    PayTansyoPay2 char(9),
    PayTansyoNinki2 char(2),
    PayTansyoUmaban3 char(2),
    PayTansyoPay3 char(9),
    PayTansyoNinki3 char(2),
    PayFukusyoUmaban1 char(2),
    PayFukusyoPay1 char(9),
    PayFukusyoNinki1 char(2),
    PayFukusyoUmaban2 char(2),
    PayFukusyoPay2 char(9),
    PayFukusyoNinki2 char(2),
    PayFukusyoUmaban3 char(2),
    PayFukusyoPay3 char(9),
    PayFukusyoNinki3 char(2),
    PayFukusyoUmaban4 char(2),
    PayFukusyoPay4 char(9),
    PayFukusyoNinki4 char(2),
    PayFukusyoUmaban5 char(2),
    PayFukusyoPay5 char(9),
    PayFukusyoNinki5 char(2),
    PayWakurenKumi1 char(2),
    PayWakurenPay1 char(9),
    PayWakurenNinki1 char(2),
    PayWakurenKumi2 char(2),
    PayWakurenPay2 char(9),
    PayWakurenNinki2 char(2),
    PayWakurenKumi3 char(2),
    PayWakurenPay3 char(9),
    PayWakurenNinki3 char(2),
    PayUmarenKumi1 char(4),
    PayUmarenPay1 char(9),
    PayUmarenNinki1 char(3),
    PayUmarenKumi2 char(4),
    PayUmarenPay2 char(9),
    PayUmarenNinki2 char(3),
    PayUmarenKumi3 char(4),
    PayUmarenPay3 char(9),
    PayUmarenNinki3 char(3),
    PayWideKumi1 char(4),
    PayWidePay1 char(9),
    PayWideNinki1 char(3),
    PayWideKumi2 char(4),
    PayWidePay2 char(9),
    PayWideNinki2 char(3),
    PayWideKumi3 char(4),
    PayWidePay3 char(9),
    PayWideNinki3 char(3),
    PayWideKumi4 char(4),
    PayWidePay4 char(9),
    PayWideNinki4 char(3),
    PayWideKumi5 char(4),
    PayWidePay5 char(9),
    PayWideNinki5 char(3),
    PayWideKumi6 char(4),
    PayWidePay6 char(9),
    PayWideNinki6 char(3),
    PayWideKumi7 char(4),
    PayWidePay7 char(9),
    PayWideNinki7 char(3),
    PayReserved1Kumi1 char(4),
    PayReserved1Pay1 char(9),
    PayReserved1Ninki1 char(3),
    PayReserved1Kumi2 char(4),
    PayReserved1Pay2 char(9),
    PayReserved1Ninki2 char(3),
    PayReserved1Kumi3 char(4),
    PayReserved1Pay3 char(9),
    PayReserved1Ninki3 char(3),
    PayUmatanKumi1 char(4),
    PayUmatanPay1 char(9),
    PayUmatanNinki1 char(3),
    PayUmatanKumi2 char(4),
    PayUmatanPay2 char(9),
    PayUmatanNinki2 char(3),
    PayUmatanKumi3 char(4),
    PayUmatanPay3 char(9),
    PayUmatanNinki3 char(3),
    PayUmatanKumi4 char(4),
    PayUmatanPay4 char(9),
    PayUmatanNinki4 char(3),
    PayUmatanKumi5 char(4),
    PayUmatanPay5 char(9),
    PayUmatanNinki5 char(3),
    PayUmatanKumi6 char(4),
    PayUmatanPay6 char(9),
    PayUmatanNinki6 char(3),
    PaySanrenpukuKumi1 char(6),
    PaySanrenpukuPay1 char(9),
    PaySanrenpukuNinki1 char(3),
    PaySanrenpukuKumi2 char(6),
    PaySanrenpukuPay2 char(9),
    PaySanrenpukuNinki2 char(3),
    PaySanrenpukuKumi3 char(6),
    PaySanrenpukuPay3 char(9),
    PaySanrenpukuNinki3 char(3),
    PaySanrentanKumi1 char(6),
    PaySanrentanPay1 char(9),
    PaySanrentanNinki1 char(4),
    PaySanrentanKumi2 char(6),
    PaySanrentanPay2 char(9),
    PaySanrentanNinki2 char(4),
    PaySanrentanKumi3 char(6),
    PaySanrentanPay3 char(9),
    PaySanrentanNinki3 char(4),
    PaySanrentanKumi4 char(6),
    PaySanrentanPay4 char(9),
    PaySanrentanNinki4 char(4),
    PaySanrentanKumi5 char(6),
    PaySanrentanPay5 char(9),
    PaySanrentanNinki5 char(4),
    PaySanrentanKumi6 char(6),
    PaySanrentanPay6 char(9),
    PaySanrentanNinki6 char(4),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
);

CREATE TABLE HASSOU_JIKOKU_CHANGE
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    HappyoTime char(8),
    AtoJi char(2),
    AtoFun char(2),
    MaeJi char(2),
    MaeFun char(2),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, HappyoTime)
);

CREATE TABLE HYOSU
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    TorokuTosu char(2),
    SyussoTosu char(2),
    HatubaiFlag1 char(1),
    HatubaiFlag2 char(1),
    HatubaiFlag3 char(1),
    HatubaiFlag4 char(1),
    HatubaiFlag5 char(1),
    HatubaiFlag6 char(1),
    HatubaiFlag7 char(1),
    FukuChakuBaraiKey char(1),
    HenkanUma1 char(1),
    HenkanUma2 char(1),
    HenkanUma3 char(1),
    HenkanUma4 char(1),
    HenkanUma5 char(1),
    HenkanUma6 char(1),
    HenkanUma7 char(1),
    HenkanUma8 char(1),
    HenkanUma9 char(1),
    HenkanUma10 char(1),
    HenkanUma11 char(1),
    HenkanUma12 char(1),
    HenkanUma13 char(1),
    HenkanUma14 char(1),
    HenkanUma15 char(1),
    HenkanUma16 char(1),
    HenkanUma17 char(1),
    HenkanUma18 char(1),
    HenkanUma19 char(1),
    HenkanUma20 char(1),
    HenkanUma21 char(1),
    HenkanUma22 char(1),
    HenkanUma23 char(1),
    HenkanUma24 char(1),
    HenkanUma25 char(1),
    HenkanUma26 char(1),
    HenkanUma27 char(1),
    HenkanUma28 char(1),
    HenkanWaku1 char(1),
    HenkanWaku2 char(1),
    HenkanWaku3 char(1),
    HenkanWaku4 char(1),
    HenkanWaku5 char(1),
    HenkanWaku6 char(1),
    HenkanWaku7 char(1),
    HenkanWaku8 char(1),
    HenkanDoWaku1 char(1),
    HenkanDoWaku2 char(1),
    HenkanDoWaku3 char(1),
    HenkanDoWaku4 char(1),
    HenkanDoWaku5 char(1),
    HenkanDoWaku6 char(1),
    HenkanDoWaku7 char(1),
    HenkanDoWaku8 char(1),
    HyoTotal1 char(11),
    HyoTotal2 char(11),
    HyoTotal3 char(11),
    HyoTotal4 char(11),
    HyoTotal5 char(11),
    HyoTotal6 char(11),
    HyoTotal7 char(11),
    HyoTotal8 char(11),
    HyoTotal9 char(11),
    HyoTotal10 char(11),
    HyoTotal11 char(11),
    HyoTotal12 char(11),
    HyoTotal13 char(11),
    HyoTotal14 char(11),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
);

CREATE TABLE HYOSU_SANREN
(
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    Kumi char(6),
    Hyo char(11),
    Ninki char(3),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
);

CREATE TABLE HYOSU_SANRENTAN
(
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    Kumi char(6),
    Hyo char(11),
    Ninki char(4),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
);

CREATE TABLE HYOSU_TANPUKU
(
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    Umaban char(2),
    TanHyo char(11),
    TanNinki char(2),
    FukuHyo char(11),
    FukuNinki char(2),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
);

CREATE TABLE HYOSU_UMARENWIDE
(
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    Kumi char(4),
    UmarenHyo char(11),
    UmarenNinki char(3),
    WideHyo char(11),
    WideNinki char(3),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
);

CREATE TABLE HYOSU_UMATAN
(
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    Kumi char(4),
    Hyo char(11),
    Ninki char(3),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
);

CREATE TABLE HYOSU_WAKU
(
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    Kumi char(2),
    Hyo char(11),
    Ninki char(2),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
);

CREATE TABLE HYOSU2
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    TorokuTosu char(2),
    SyussoTosu char(2),
    HatubaiFlag1 char(1),
    HenkanUma1 char(1),
    HenkanUma2 char(1),
    HenkanUma3 char(1),
    HenkanUma4 char(1),
    HenkanUma5 char(1),
    HenkanUma6 char(1),
    HenkanUma7 char(1),
    HenkanUma8 char(1),
    HenkanUma9 char(1),
    HenkanUma10 char(1),
    HenkanUma11 char(1),
    HenkanUma12 char(1),
    HenkanUma13 char(1),
    HenkanUma14 char(1),
    HenkanUma15 char(1),
    HenkanUma16 char(1),
    HenkanUma17 char(1),
    HenkanUma18 char(1),
    HyoTotal1 char(11),
    HyoTotal2 char(11),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
);

CREATE TABLE KEITO
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    HansyokuNum char(8),
    KeitoId char(30),
    KeitoName char(36),
    KeitoEx text,
    PRIMARY KEY (HansyokuNum)
);

CREATE TABLE KISYU
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    KisyuCode char(5),
    DelKubun char(1),
    IssueDate char(8),
    DelDate char(8),
    BirthDate char(8),
    KisyuName char(34),
    reserved char(34),
    KisyuNameKana char(30),
    KisyuRyakusyo char(8),
    KisyuNameEng char(80),
    SexCD char(1),
    SikakuCD char(1),
    MinaraiCD char(1),
    TozaiCD char(1),
    Syotai char(20),
    ChokyosiCode char(5),
    ChokyosiRyakusyo char(8),
    HatuKiJyo1Hatukijyoid char(16),
    HatuKiJyo1SyussoTosu char(2),
    HatuKiJyo1KettoNum char(10),
    HatuKiJyo1Bamei char(36),
    HatuKiJyo1KakuteiJyuni char(2),
    HatuKiJyo1IJyoCD char(1),
    HatuKiJyo2Hatukijyoid char(16),
    HatuKiJyo2SyussoTosu char(2),
    HatuKiJyo2KettoNum char(10),
    HatuKiJyo2Bamei char(36),
    HatuKiJyo2KakuteiJyuni char(2),
    HatuKiJyo2IJyoCD char(1),
    HatuSyori1Hatusyoriid char(16),
    HatuSyori1SyussoTosu char(2),
    HatuSyori1KettoNum char(10),
    HatuSyori1Bamei char(36),
    HatuSyori2Hatusyoriid char(16),
    HatuSyori2SyussoTosu char(2),
    HatuSyori2KettoNum char(10),
    HatuSyori2Bamei char(36),
    SaikinJyusyo1SaikinJyusyoid char(16),
    SaikinJyusyo1Hondai char(60),
    SaikinJyusyo1Ryakusyo10 char(20),
    SaikinJyusyo1Ryakusyo6 char(12),
    SaikinJyusyo1Ryakusyo3 char(6),
    SaikinJyusyo1GradeCD char(1),
    SaikinJyusyo1SyussoTosu char(2),
    SaikinJyusyo1KettoNum char(10),
    SaikinJyusyo1Bamei char(36),
    SaikinJyusyo2SaikinJyusyoid char(16),
    SaikinJyusyo2Hondai char(60),
    SaikinJyusyo2Ryakusyo10 char(20),
    SaikinJyusyo2Ryakusyo6 char(12),
    SaikinJyusyo2Ryakusyo3 char(6),
    SaikinJyusyo2GradeCD char(1),
    SaikinJyusyo2SyussoTosu char(2),
    SaikinJyusyo2KettoNum char(10),
    SaikinJyusyo2Bamei char(36),
    SaikinJyusyo3SaikinJyusyoid char(16),
    SaikinJyusyo3Hondai char(60),
    SaikinJyusyo3Ryakusyo10 char(20),
    SaikinJyusyo3Ryakusyo6 char(12),
    SaikinJyusyo3Ryakusyo3 char(6),
    SaikinJyusyo3GradeCD char(1),
    SaikinJyusyo3SyussoTosu char(2),
    SaikinJyusyo3KettoNum char(10),
    SaikinJyusyo3Bamei char(36),
    PRIMARY KEY (KisyuCode)
);

CREATE TABLE KISYU_CHANGE
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    HappyoTime char(8),
    Umaban char(2),
    Bamei char(36),
    AtoFutan char(3),
    AtoKisyuCode char(5),
    AtoKisyuName char(34),
    AtoMinaraiCD char(1),
    MaeFutan char(3),
    MaeKisyuCode char(5),
    MaeKisyuName char(34),
    MaeMinaraiCD char(1),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, HappyoTime, Umaban)
);

CREATE TABLE KISYU_SEISEKI
(
    MakeDate char(8),
    KisyuCode char(5),
    Num char(1),
    SetYear char(4),
    HonSyokinHeichi char(10),
    HonSyokinSyogai char(10),
    FukaSyokinHeichi char(10),
    FukaSyokinSyogai char(10),
    HeichiChakukaisu1 char(6),
    HeichiChakukaisu2 char(6),
    HeichiChakukaisu3 char(6),
    HeichiChakukaisu4 char(6),
    HeichiChakukaisu5 char(6),
    HeichiChakukaisu6 char(6),
    SyogaiChakukaisu1 char(6),
    SyogaiChakukaisu2 char(6),
    SyogaiChakukaisu3 char(6),
    SyogaiChakukaisu4 char(6),
    SyogaiChakukaisu5 char(6),
    SyogaiChakukaisu6 char(6),
    Jyo1Chakukaisu1 char(6),
    Jyo1Chakukaisu2 char(6),
    Jyo1Chakukaisu3 char(6),
    Jyo1Chakukaisu4 char(6),
    Jyo1Chakukaisu5 char(6),
    Jyo1Chakukaisu6 char(6),
    Jyo2Chakukaisu1 char(6),
    Jyo2Chakukaisu2 char(6),
    Jyo2Chakukaisu3 char(6),
    Jyo2Chakukaisu4 char(6),
    Jyo2Chakukaisu5 char(6),
    Jyo2Chakukaisu6 char(6),
    Jyo3Chakukaisu1 char(6),
    Jyo3Chakukaisu2 char(6),
    Jyo3Chakukaisu3 char(6),
    Jyo3Chakukaisu4 char(6),
    Jyo3Chakukaisu5 char(6),
    Jyo3Chakukaisu6 char(6),
    Jyo4Chakukaisu1 char(6),
    Jyo4Chakukaisu2 char(6),
    Jyo4Chakukaisu3 char(6),
    Jyo4Chakukaisu4 char(6),
    Jyo4Chakukaisu5 char(6),
    Jyo4Chakukaisu6 char(6),
    Jyo5Chakukaisu1 char(6),
    Jyo5Chakukaisu2 char(6),
    Jyo5Chakukaisu3 char(6),
    Jyo5Chakukaisu4 char(6),
    Jyo5Chakukaisu5 char(6),
    Jyo5Chakukaisu6 char(6),
    Jyo6Chakukaisu1 char(6),
    Jyo6Chakukaisu2 char(6),
    Jyo6Chakukaisu3 char(6),
    Jyo6Chakukaisu4 char(6),
    Jyo6Chakukaisu5 char(6),
    Jyo6Chakukaisu6 char(6),
    Jyo7Chakukaisu1 char(6),
    Jyo7Chakukaisu2 char(6),
    Jyo7Chakukaisu3 char(6),
    Jyo7Chakukaisu4 char(6),
    Jyo7Chakukaisu5 char(6),
    Jyo7Chakukaisu6 char(6),
    Jyo8Chakukaisu1 char(6),
    Jyo8Chakukaisu2 char(6),
    Jyo8Chakukaisu3 char(6),
    Jyo8Chakukaisu4 char(6),
    Jyo8Chakukaisu5 char(6),
    Jyo8Chakukaisu6 char(6),
    Jyo9Chakukaisu1 char(6),
    Jyo9Chakukaisu2 char(6),
    Jyo9Chakukaisu3 char(6),
    Jyo9Chakukaisu4 char(6),
    Jyo9Chakukaisu5 char(6),
    Jyo9Chakukaisu6 char(6),
    Jyo10Chakukaisu1 char(6),
    Jyo10Chakukaisu2 char(6),
    Jyo10Chakukaisu3 char(6),
    Jyo10Chakukaisu4 char(6),
    Jyo10Chakukaisu5 char(6),
    Jyo10Chakukaisu6 char(6),
    Jyo11Chakukaisu1 char(6),
    Jyo11Chakukaisu2 char(6),
    Jyo11Chakukaisu3 char(6),
    Jyo11Chakukaisu4 char(6),
    Jyo11Chakukaisu5 char(6),
    Jyo11Chakukaisu6 char(6),
    Jyo12Chakukaisu1 char(6),
    Jyo12Chakukaisu2 char(6),
    Jyo12Chakukaisu3 char(6),
    Jyo12Chakukaisu4 char(6),
    Jyo12Chakukaisu5 char(6),
    Jyo12Chakukaisu6 char(6),
    Jyo13Chakukaisu1 char(6),
    Jyo13Chakukaisu2 char(6),
    Jyo13Chakukaisu3 char(6),
    Jyo13Chakukaisu4 char(6),
    Jyo13Chakukaisu5 char(6),
    Jyo13Chakukaisu6 char(6),
    Jyo14Chakukaisu1 char(6),
    Jyo14Chakukaisu2 char(6),
    Jyo14Chakukaisu3 char(6),
    Jyo14Chakukaisu4 char(6),
    Jyo14Chakukaisu5 char(6),
    Jyo14Chakukaisu6 char(6),
    Jyo15Chakukaisu1 char(6),
    Jyo15Chakukaisu2 char(6),
    Jyo15Chakukaisu3 char(6),
    Jyo15Chakukaisu4 char(6),
    Jyo15Chakukaisu5 char(6),
    Jyo15Chakukaisu6 char(6),
    Jyo16Chakukaisu1 char(6),
    Jyo16Chakukaisu2 char(6),
    Jyo16Chakukaisu3 char(6),
    Jyo16Chakukaisu4 char(6),
    Jyo16Chakukaisu5 char(6),
    Jyo16Chakukaisu6 char(6),
    Jyo17Chakukaisu1 char(6),
    Jyo17Chakukaisu2 char(6),
    Jyo17Chakukaisu3 char(6),
    Jyo17Chakukaisu4 char(6),
    Jyo17Chakukaisu5 char(6),
    Jyo17Chakukaisu6 char(6),
    Jyo18Chakukaisu1 char(6),
    Jyo18Chakukaisu2 char(6),
    Jyo18Chakukaisu3 char(6),
    Jyo18Chakukaisu4 char(6),
    Jyo18Chakukaisu5 char(6),
    Jyo18Chakukaisu6 char(6),
    Jyo19Chakukaisu1 char(6),
    Jyo19Chakukaisu2 char(6),
    Jyo19Chakukaisu3 char(6),
    Jyo19Chakukaisu4 char(6),
    Jyo19Chakukaisu5 char(6),
    Jyo19Chakukaisu6 char(6),
    Jyo20Chakukaisu1 char(6),
    Jyo20Chakukaisu2 char(6),
    Jyo20Chakukaisu3 char(6),
    Jyo20Chakukaisu4 char(6),
    Jyo20Chakukaisu5 char(6),
    Jyo20Chakukaisu6 char(6),
    Kyori1Chakukaisu1 char(6),
    Kyori1Chakukaisu2 char(6),
    Kyori1Chakukaisu3 char(6),
    Kyori1Chakukaisu4 char(6),
    Kyori1Chakukaisu5 char(6),
    Kyori1Chakukaisu6 char(6),
    Kyori2Chakukaisu1 char(6),
    Kyori2Chakukaisu2 char(6),
    Kyori2Chakukaisu3 char(6),
    Kyori2Chakukaisu4 char(6),
    Kyori2Chakukaisu5 char(6),
    Kyori2Chakukaisu6 char(6),
    Kyori3Chakukaisu1 char(6),
    Kyori3Chakukaisu2 char(6),
    Kyori3Chakukaisu3 char(6),
    Kyori3Chakukaisu4 char(6),
    Kyori3Chakukaisu5 char(6),
    Kyori3Chakukaisu6 char(6),
    Kyori4Chakukaisu1 char(6),
    Kyori4Chakukaisu2 char(6),
    Kyori4Chakukaisu3 char(6),
    Kyori4Chakukaisu4 char(6),
    Kyori4Chakukaisu5 char(6),
    Kyori4Chakukaisu6 char(6),
    Kyori5Chakukaisu1 char(6),
    Kyori5Chakukaisu2 char(6),
    Kyori5Chakukaisu3 char(6),
    Kyori5Chakukaisu4 char(6),
    Kyori5Chakukaisu5 char(6),
    Kyori5Chakukaisu6 char(6),
    Kyori6Chakukaisu1 char(6),
    Kyori6Chakukaisu2 char(6),
    Kyori6Chakukaisu3 char(6),
    Kyori6Chakukaisu4 char(6),
    Kyori6Chakukaisu5 char(6),
    Kyori6Chakukaisu6 char(6),
    PRIMARY KEY (KisyuCode, Num)
);

CREATE TABLE MINING
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    MakeHM char(4),
    Umaban1 char(2),
    DMTime1 char(5),
    DMGosaP1 char(4),
    DMGosaM1 char(4),
    Umaban2 char(2),
    DMTime2 char(5),
    DMGosaP2 char(4),
    DMGosaM2 char(4),
    Umaban3 char(2),
    DMTime3 char(5),
    DMGosaP3 char(4),
    DMGosaM3 char(4),
    Umaban4 char(2),
    DMTime4 char(5),
    DMGosaP4 char(4),
    DMGosaM4 char(4),
    Umaban5 char(2),
    DMTime5 char(5),
    DMGosaP5 char(4),
    DMGosaM5 char(4),
    Umaban6 char(2),
    DMTime6 char(5),
    DMGosaP6 char(4),
    DMGosaM6 char(4),
    Umaban7 char(2),
    DMTime7 char(5),
    DMGosaP7 char(4),
    DMGosaM7 char(4),
    Umaban8 char(2),
    DMTime8 char(5),
    DMGosaP8 char(4),
    DMGosaM8 char(4),
    Umaban9 char(2),
    DMTime9 char(5),
    DMGosaP9 char(4),
    DMGosaM9 char(4),
    Umaban10 char(2),
    DMTime10 char(5),
    DMGosaP10 char(4),
    DMGosaM10 char(4),
    Umaban11 char(2),
    DMTime11 char(5),
    DMGosaP11 char(4),
    DMGosaM11 char(4),
    Umaban12 char(2),
    DMTime12 char(5),
    DMGosaP12 char(4),
    DMGosaM12 char(4),
    Umaban13 char(2),
    DMTime13 char(5),
    DMGosaP13 char(4),
    DMGosaM13 char(4),
    Umaban14 char(2),
    DMTime14 char(5),
    DMGosaP14 char(4),
    DMGosaM14 char(4),
    Umaban15 char(2),
    DMTime15 char(5),
    DMGosaP15 char(4),
    DMGosaM15 char(4),
    Umaban16 char(2),
    DMTime16 char(5),
    DMGosaP16 char(4),
    DMGosaM16 char(4),
    Umaban17 char(2),
    DMTime17 char(5),
    DMGosaP17 char(4),
    DMGosaM17 char(4),
    Umaban18 char(2),
    DMTime18 char(5),
    DMGosaP18 char(4),
    DMGosaM18 char(4),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
);

CREATE TABLE ODDS_SANREN
(
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    Kumi char(6),
    Odds char(6),
    Ninki char(3),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
);

CREATE TABLE ODDS_SANREN_HEAD
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    HappyoTime char(8),
    TorokuTosu char(2),
    SyussoTosu char(2),
    SanrenFlag char(1),
    TotalHyosuSanren char(11),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
);

CREATE TABLE ODDS_SANRENTAN
(
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    Kumi char(6),
    Odds char(7),
    Ninki char(4),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
);

CREATE TABLE ODDS_SANRENTAN_HEAD
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    HappyoTime char(8),
    TorokuTosu char(2),
    SyussoTosu char(2),
    SanrentanFlag char(1),
    TotalHyosuSanrentan char(11),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
);

CREATE TABLE ODDS_TANPUKU
(
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    Umaban char(2),
    TanOdds char(4),
    TanNinki char(2),
    FukuOddsLow char(4),
    FukuOddsHigh char(4),
    FukuNinki char(2),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
);

CREATE TABLE ODDS_TANPUKUWAKU_HEAD
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    HappyoTime char(8),
    TorokuTosu char(2),
    SyussoTosu char(2),
    TansyoFlag char(1),
    FukusyoFlag char(1),
    WakurenFlag char(1),
    FukuChakuBaraiKey char(1),
    TotalHyosuTansyo char(11),
    TotalHyosuFukusyo char(11),
    TotalHyosuWakuren char(11),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
);

CREATE TABLE ODDS_UMAREN
(
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    Kumi char(4),
    Odds char(6),
    Ninki char(3),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
);

CREATE TABLE ODDS_UMAREN_HEAD
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    HappyoTime char(8),
    TorokuTosu char(2),
    SyussoTosu char(2),
    UmarenFlag char(1),
    TotalHyosuUmaren char(11),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
);

CREATE TABLE ODDS_UMATAN
(
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    Kumi char(4),
    Odds char(6),
    Ninki char(3),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
);

CREATE TABLE ODDS_UMATAN_HEAD
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    HappyoTime char(8),
    TorokuTosu char(2),
    SyussoTosu char(2),
    UmatanFlag char(1),
    TotalHyosuUmatan char(11),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
);

CREATE TABLE ODDS_WAKU
(
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    Kumi char(2),
    Odds char(5),
    Ninki char(2),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
);

CREATE TABLE ODDS_WIDE
(
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    Kumi char(4),
    OddsLow char(5),
    OddsHigh char(5),
    Ninki char(3),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
);

CREATE TABLE ODDS_WIDE_HEAD
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    HappyoTime char(8),
    TorokuTosu char(2),
    SyussoTosu char(2),
    WideFlag char(1),
    TotalHyosuWide char(11),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
);

CREATE TABLE RACE
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    YoubiCD char(1),
    TokuNum char(4),
    Hondai char(60),
    Fukudai char(60),
    Kakko char(60),
    HondaiEng char(120),
    FukudaiEng char(120),
    KakkoEng char(120),
    Ryakusyo10 char(20),
    Ryakusyo6 char(12),
    Ryakusyo3 char(6),
    Kubun char(1),
    Nkai char(3),
    GradeCD char(1),
    GradeCDBefore char(1),
    SyubetuCD char(2),
    KigoCD char(3),
    JyuryoCD char(1),
    JyokenCD1 char(3),
    JyokenCD2 char(3),
    JyokenCD3 char(3),
    JyokenCD4 char(3),
    JyokenCD5 char(3),
    JyokenName char(60),
    Kyori char(4),
    KyoriBefore char(4),
    TrackCD char(2),
    TrackCDBefore char(2),
    CourseKubunCD char(2),
    CourseKubunCDBefore char(2),
    Honsyokin1 char(8),
    Honsyokin2 char(8),
    Honsyokin3 char(8),
    Honsyokin4 char(8),
    Honsyokin5 char(8),
    Honsyokin6 char(8),
    Honsyokin7 char(8),
    HonsyokinBefore1 char(8),
    HonsyokinBefore2 char(8),
    HonsyokinBefore3 char(8),
    HonsyokinBefore4 char(8),
    HonsyokinBefore5 char(8),
    Fukasyokin1 char(8),
    Fukasyokin2 char(8),
    Fukasyokin3 char(8),
    Fukasyokin4 char(8),
    Fukasyokin5 char(8),
    FukasyokinBefore1 char(8),
    FukasyokinBefore2 char(8),
    FukasyokinBefore3 char(8),
    HassoTime char(4),
    HassoTimeBefore char(4),
    TorokuTosu char(2),
    SyussoTosu char(2),
    NyusenTosu char(2),
    TenkoCD char(1),
    SibaBabaCD char(1),
    DirtBabaCD char(1),
    LapTime1 char(3),
    LapTime2 char(3),
    LapTime3 char(3),
    LapTime4 char(3),
    LapTime5 char(3),
    LapTime6 char(3),
    LapTime7 char(3),
    LapTime8 char(3),
    LapTime9 char(3),
    LapTime10 char(3),
    LapTime11 char(3),
    LapTime12 char(3),
    LapTime13 char(3),
    LapTime14 char(3),
    LapTime15 char(3),
    LapTime16 char(3),
    LapTime17 char(3),
    LapTime18 char(3),
    LapTime19 char(3),
    LapTime20 char(3),
    LapTime21 char(3),
    LapTime22 char(3),
    LapTime23 char(3),
    LapTime24 char(3),
    LapTime25 char(3),
    SyogaiMileTime char(4),
    HaronTimeS3 char(3),
    HaronTimeS4 char(3),
    HaronTimeL3 char(3),
    HaronTimeL4 char(3),
    Corner1 char(1),
    Syukaisu1 char(1),
    Jyuni1 char(70),
    Corner2 char(1),
    Syukaisu2 char(1),
    Jyuni2 char(70),
    Corner3 char(1),
    Syukaisu3 char(1),
    Jyuni3 char(70),
    Corner4 char(1),
    Syukaisu4 char(1),
    Jyuni4 char(70),
    RecordUpKubun char(1),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
);

CREATE TABLE RECORD
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    RecInfoKubun char(1),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    TokuNum char(4),
    Hondai char(60),
    GradeCD char(1),
    SyubetuCD_TrackCD char(4),
    Kyori char(4),
    RecKubun char(1),
    RecTime char(4),
    TenkoCD char(1),
    SibaBabaCD char(1),
    DirtBabaCD char(1),
    RecUmaKettoNum1 char(10),
    RecUmaBamei1 char(36),
    RecUmaUmaKigoCD1 char(2),
    RecUmaSexCD1 char(1),
    RecUmaChokyosiCode1 char(5),
    RecUmaChokyosiName1 char(34),
    RecUmaFutan1 char(3),
    RecUmaKisyuCode1 char(5),
    RecUmaKisyuName1 char(34),
    RecUmaKettoNum2 char(10),
    RecUmaBamei2 char(36),
    RecUmaUmaKigoCD2 char(2),
    RecUmaSexCD2 char(1),
    RecUmaChokyosiCode2 char(5),
    RecUmaChokyosiName2 char(34),
    RecUmaFutan2 char(3),
    RecUmaKisyuCode2 char(5),
    RecUmaKisyuName2 char(34),
    RecUmaKettoNum3 char(10),
    RecUmaBamei3 char(36),
    RecUmaUmaKigoCD3 char(2),
    RecUmaSexCD3 char(1),
    RecUmaChokyosiCode3 char(5),
    RecUmaChokyosiName3 char(34),
    RecUmaFutan3 char(3),
    RecUmaKisyuCode3 char(5),
    RecUmaKisyuName3 char(34),
    PRIMARY KEY (RecInfoKubun, Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, TokuNum, SyubetuCD_TrackCD, Kyori)
);

CREATE TABLE SALE
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    KettoNum char(10),
    HansyokuFNum char(8),
    HansyokuMNum char(8),
    BirthYear char(4),
    SaleCode char(6),
    SaleHostName char(40),
    SaleName char(80),
    FromDate char(8),
    ToDate char(8),
    Barei char(1),
    Price char(10),
    PRIMARY KEY (KettoNum, SaleCode, FromDate)
);

CREATE TABLE SANKU
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    KettoNum char(10),
    BirthDate char(8),
    SexCD char(1),
    HinsyuCD char(1),
    KeiroCD char(2),
    SankuMochiKubun char(1),
    ImportYear char(4),
    BreederCode char(6),
    SanchiName char(20),
    FNum char(8),
    MNum char(8),
    FFNum char(8),
    FMNum char(8),
    MFNum char(8),
    MMNum char(8),
    FFFNum char(8),
    FFMNum char(8),
    FMFNum char(8),
    FMMNum char(8),
    MFFNum char(8),
    MFMNum char(8),
    MMFNum char(8),
    MMMNum char(8),
    PRIMARY KEY (KettoNum)
);

CREATE TABLE SCHEDULE
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    YoubiCD char(1),
    Jyusyo1TokuNum char(4),
    Jyusyo1Hondai char(60),
    Jyusyo1Ryakusyo10 char(20),
    Jyusyo1Ryakusyo6 char(12),
    Jyusyo1Ryakusyo3 char(6),
    Jyusyo1Nkai char(3),
    Jyusyo1GradeCD char(1),
    Jyusyo1SyubetuCD char(2),
    Jyusyo1KigoCD char(3),
    Jyusyo1JyuryoCD char(1),
    Jyusyo1Kyori char(4),
    Jyusyo1TrackCD char(2),
    Jyusyo2TokuNum char(4),
    Jyusyo2Hondai char(60),
    Jyusyo2Ryakusyo10 char(20),
    Jyusyo2Ryakusyo6 char(12),
    Jyusyo2Ryakusyo3 char(6),
    Jyusyo2Nkai char(3),
    Jyusyo2GradeCD char(1),
    Jyusyo2SyubetuCD char(2),
    Jyusyo2KigoCD char(3),
    Jyusyo2JyuryoCD char(1),
    Jyusyo2Kyori char(4),
    Jyusyo2TrackCD char(2),
    Jyusyo3TokuNum char(4),
    Jyusyo3Hondai char(60),
    Jyusyo3Ryakusyo10 char(20),
    Jyusyo3Ryakusyo6 char(12),
    Jyusyo3Ryakusyo3 char(6),
    Jyusyo3Nkai char(3),
    Jyusyo3GradeCD char(1),
    Jyusyo3SyubetuCD char(2),
    Jyusyo3KigoCD char(3),
    Jyusyo3JyuryoCD char(1),
    Jyusyo3Kyori char(4),
    Jyusyo3TrackCD char(2),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji)
);

CREATE TABLE SEISAN
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    BreederCode char(6),
    BreederName_Co char(70),
    BreederName char(70),
    BreederNameKana char(70),
    BreederNameEng char(168),
    Address char(20),
    H_SetYear char(4),
    H_HonSyokinTotal char(10),
    H_FukaSyokin char(10),
    H_ChakuKaisu1 char(6),
    H_ChakuKaisu2 char(6),
    H_ChakuKaisu3 char(6),
    H_ChakuKaisu4 char(6),
    H_ChakuKaisu5 char(6),
    H_ChakuKaisu6 char(6),
    R_SetYear char(4),
    R_HonSyokinTotal char(10),
    R_FukaSyokin char(10),
    R_ChakuKaisu1 char(6),
    R_ChakuKaisu2 char(6),
    R_ChakuKaisu3 char(6),
    R_ChakuKaisu4 char(6),
    R_ChakuKaisu5 char(6),
    R_ChakuKaisu6 char(6),
    PRIMARY KEY (BreederCode)
);

CREATE TABLE TENKO_BABA
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    HappyoTime char(8),
    HenkoID char(1),
    AtoTenkoCD char(1),
    AtoSibaBabaCD char(1),
    AtoDirtBabaCD char(1),
    MaeTenkoCD char(1),
    MaeSibaBabaCD char(1),
    MaeDirtBabaCD char(1),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, HappyoTime, HenkoID)
);

CREATE TABLE TOKU
(
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    Num char(3),
    KettoNum char(10),
    Bamei char(36),
    UmaKigoCD char(2),
    SexCD char(1),
    TozaiCD char(1),
    ChokyosiCode char(5),
    ChokyosiRyakusyo char(8),
    Futan char(3),
    Koryu char(1),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Num)
);

CREATE TABLE TOKU_RACE
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    YoubiCD char(1),
    TokuNum char(4),
    Hondai char(60),
    Fukudai char(60),
    Kakko char(60),
    HondaiEng char(120),
    FukudaiEng char(120),
    KakkoEng char(120),
    Ryakusyo10 char(20),
    Ryakusyo6 char(12),
    Ryakusyo3 char(6),
    Kubun char(1),
    Nkai char(3),
    GradeCD char(1),
    SyubetuCD char(2),
    KigoCD char(3),
    JyuryoCD char(1),
    JyokenCD1 char(3),
    JyokenCD2 char(3),
    JyokenCD3 char(3),
    JyokenCD4 char(3),
    JyokenCD5 char(3),
    Kyori char(4),
    TrackCD char(2),
    CourseKubunCD char(2),
    HandiDate char(8),
    TorokuTosu char(3),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
);

CREATE TABLE TORIKESI_JYOGAI
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    HappyoTime char(8),
    Umaban char(2),
    Bamei char(36),
    JiyuKubun char(3),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
);

CREATE TABLE UMA
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    KettoNum char(10),
    DelKubun char(1),
    RegDate char(8),
    DelDate char(8),
    BirthDate char(8),
    Bamei char(36),
    BameiKana char(36),
    BameiEng char(60),
    ZaikyuFlag char(1),
    Reserved char(19),
    UmaKigoCD char(2),
    SexCD char(1),
    HinsyuCD char(1),
    KeiroCD char(2),
    Ketto3InfoHansyokuNum1 char(8),
    Ketto3InfoBamei1 char(36),
    Ketto3InfoHansyokuNum2 char(8),
    Ketto3InfoBamei2 char(36),
    Ketto3InfoHansyokuNum3 char(8),
    Ketto3InfoBamei3 char(36),
    Ketto3InfoHansyokuNum4 char(8),
    Ketto3InfoBamei4 char(36),
    Ketto3InfoHansyokuNum5 char(8),
    Ketto3InfoBamei5 char(36),
    Ketto3InfoHansyokuNum6 char(8),
    Ketto3InfoBamei6 char(36),
    Ketto3InfoHansyokuNum7 char(8),
    Ketto3InfoBamei7 char(36),
    Ketto3InfoHansyokuNum8 char(8),
    Ketto3InfoBamei8 char(36),
    Ketto3InfoHansyokuNum9 char(8),
    Ketto3InfoBamei9 char(36),
    Ketto3InfoHansyokuNum10 char(8),
    Ketto3InfoBamei10 char(36),
    Ketto3InfoHansyokuNum11 char(8),
    Ketto3InfoBamei11 char(36),
    Ketto3InfoHansyokuNum12 char(8),
    Ketto3InfoBamei12 char(36),
    Ketto3InfoHansyokuNum13 char(8),
    Ketto3InfoBamei13 char(36),
    Ketto3InfoHansyokuNum14 char(8),
    Ketto3InfoBamei14 char(36),
    TozaiCD char(1),
    ChokyosiCode char(5),
    ChokyosiRyakusyo char(8),
    Syotai char(20),
    BreederCode char(6),
    BreederName char(70),
    SanchiName char(20),
    BanusiCode char(6),
    BanusiName char(64),
    RuikeiHonsyoHeiti char(9),
    RuikeiHonsyoSyogai char(9),
    RuikeiFukaHeichi char(9),
    RuikeiFukaSyogai char(9),
    RuikeiSyutokuHeichi char(9),
    RuikeiSyutokuSyogai char(9),
    SogoChakukaisu1 char(3),
    SogoChakukaisu2 char(3),
    SogoChakukaisu3 char(3),
    SogoChakukaisu4 char(3),
    SogoChakukaisu5 char(3),
    SogoChakukaisu6 char(3),
    ChuoChakukaisu1 char(3),
    ChuoChakukaisu2 char(3),
    ChuoChakukaisu3 char(3),
    ChuoChakukaisu4 char(3),
    ChuoChakukaisu5 char(3),
    ChuoChakukaisu6 char(3),
    Ba1Chakukaisu1 char(3),
    Ba1Chakukaisu2 char(3),
    Ba1Chakukaisu3 char(3),
    Ba1Chakukaisu4 char(3),
    Ba1Chakukaisu5 char(3),
    Ba1Chakukaisu6 char(3),
    Ba2Chakukaisu1 char(3),
    Ba2Chakukaisu2 char(3),
    Ba2Chakukaisu3 char(3),
    Ba2Chakukaisu4 char(3),
    Ba2Chakukaisu5 char(3),
    Ba2Chakukaisu6 char(3),
    Ba3Chakukaisu1 char(3),
    Ba3Chakukaisu2 char(3),
    Ba3Chakukaisu3 char(3),
    Ba3Chakukaisu4 char(3),
    Ba3Chakukaisu5 char(3),
    Ba3Chakukaisu6 char(3),
    Ba4Chakukaisu1 char(3),
    Ba4Chakukaisu2 char(3),
    Ba4Chakukaisu3 char(3),
    Ba4Chakukaisu4 char(3),
    Ba4Chakukaisu5 char(3),
    Ba4Chakukaisu6 char(3),
    Ba5Chakukaisu1 char(3),
    Ba5Chakukaisu2 char(3),
    Ba5Chakukaisu3 char(3),
    Ba5Chakukaisu4 char(3),
    Ba5Chakukaisu5 char(3),
    Ba5Chakukaisu6 char(3),
    Ba6Chakukaisu1 char(3),
    Ba6Chakukaisu2 char(3),
    Ba6Chakukaisu3 char(3),
    Ba6Chakukaisu4 char(3),
    Ba6Chakukaisu5 char(3),
    Ba6Chakukaisu6 char(3),
    Ba7Chakukaisu1 char(3),
    Ba7Chakukaisu2 char(3),
    Ba7Chakukaisu3 char(3),
    Ba7Chakukaisu4 char(3),
    Ba7Chakukaisu5 char(3),
    Ba7Chakukaisu6 char(3),
    Jyotai1Chakukaisu1 char(3),
    Jyotai1Chakukaisu2 char(3),
    Jyotai1Chakukaisu3 char(3),
    Jyotai1Chakukaisu4 char(3),
    Jyotai1Chakukaisu5 char(3),
    Jyotai1Chakukaisu6 char(3),
    Jyotai2Chakukaisu1 char(3),
    Jyotai2Chakukaisu2 char(3),
    Jyotai2Chakukaisu3 char(3),
    Jyotai2Chakukaisu4 char(3),
    Jyotai2Chakukaisu5 char(3),
    Jyotai2Chakukaisu6 char(3),
    Jyotai3Chakukaisu1 char(3),
    Jyotai3Chakukaisu2 char(3),
    Jyotai3Chakukaisu3 char(3),
    Jyotai3Chakukaisu4 char(3),
    Jyotai3Chakukaisu5 char(3),
    Jyotai3Chakukaisu6 char(3),
    Jyotai4Chakukaisu1 char(3),
    Jyotai4Chakukaisu2 char(3),
    Jyotai4Chakukaisu3 char(3),
    Jyotai4Chakukaisu4 char(3),
    Jyotai4Chakukaisu5 char(3),
    Jyotai4Chakukaisu6 char(3),
    Jyotai5Chakukaisu1 char(3),
    Jyotai5Chakukaisu2 char(3),
    Jyotai5Chakukaisu3 char(3),
    Jyotai5Chakukaisu4 char(3),
    Jyotai5Chakukaisu5 char(3),
    Jyotai5Chakukaisu6 char(3),
    Jyotai6Chakukaisu1 char(3),
    Jyotai6Chakukaisu2 char(3),
    Jyotai6Chakukaisu3 char(3),
    Jyotai6Chakukaisu4 char(3),
    Jyotai6Chakukaisu5 char(3),
    Jyotai6Chakukaisu6 char(3),
    Jyotai7Chakukaisu1 char(3),
    Jyotai7Chakukaisu2 char(3),
    Jyotai7Chakukaisu3 char(3),
    Jyotai7Chakukaisu4 char(3),
    Jyotai7Chakukaisu5 char(3),
    Jyotai7Chakukaisu6 char(3),
    Jyotai8Chakukaisu1 char(3),
    Jyotai8Chakukaisu2 char(3),
    Jyotai8Chakukaisu3 char(3),
    Jyotai8Chakukaisu4 char(3),
    Jyotai8Chakukaisu5 char(3),
    Jyotai8Chakukaisu6 char(3),
    Jyotai9Chakukaisu1 char(3),
    Jyotai9Chakukaisu2 char(3),
    Jyotai9Chakukaisu3 char(3),
    Jyotai9Chakukaisu4 char(3),
    Jyotai9Chakukaisu5 char(3),
    Jyotai9Chakukaisu6 char(3),
    Jyotai10Chakukaisu1 char(3),
    Jyotai10Chakukaisu2 char(3),
    Jyotai10Chakukaisu3 char(3),
    Jyotai10Chakukaisu4 char(3),
    Jyotai10Chakukaisu5 char(3),
    Jyotai10Chakukaisu6 char(3),
    Jyotai11Chakukaisu1 char(3),
    Jyotai11Chakukaisu2 char(3),
    Jyotai11Chakukaisu3 char(3),
    Jyotai11Chakukaisu4 char(3),
    Jyotai11Chakukaisu5 char(3),
    Jyotai11Chakukaisu6 char(3),
    Jyotai12Chakukaisu1 char(3),
    Jyotai12Chakukaisu2 char(3),
    Jyotai12Chakukaisu3 char(3),
    Jyotai12Chakukaisu4 char(3),
    Jyotai12Chakukaisu5 char(3),
    Jyotai12Chakukaisu6 char(3),
    Kyori1Chakukaisu1 char(3),
    Kyori1Chakukaisu2 char(3),
    Kyori1Chakukaisu3 char(3),
    Kyori1Chakukaisu4 char(3),
    Kyori1Chakukaisu5 char(3),
    Kyori1Chakukaisu6 char(3),
    Kyori2Chakukaisu1 char(3),
    Kyori2Chakukaisu2 char(3),
    Kyori2Chakukaisu3 char(3),
    Kyori2Chakukaisu4 char(3),
    Kyori2Chakukaisu5 char(3),
    Kyori2Chakukaisu6 char(3),
    Kyori3Chakukaisu1 char(3),
    Kyori3Chakukaisu2 char(3),
    Kyori3Chakukaisu3 char(3),
    Kyori3Chakukaisu4 char(3),
    Kyori3Chakukaisu5 char(3),
    Kyori3Chakukaisu6 char(3),
    Kyori4Chakukaisu1 char(3),
    Kyori4Chakukaisu2 char(3),
    Kyori4Chakukaisu3 char(3),
    Kyori4Chakukaisu4 char(3),
    Kyori4Chakukaisu5 char(3),
    Kyori4Chakukaisu6 char(3),
    Kyori5Chakukaisu1 char(3),
    Kyori5Chakukaisu2 char(3),
    Kyori5Chakukaisu3 char(3),
    Kyori5Chakukaisu4 char(3),
    Kyori5Chakukaisu5 char(3),
    Kyori5Chakukaisu6 char(3),
    Kyori6Chakukaisu1 char(3),
    Kyori6Chakukaisu2 char(3),
    Kyori6Chakukaisu3 char(3),
    Kyori6Chakukaisu4 char(3),
    Kyori6Chakukaisu5 char(3),
    Kyori6Chakukaisu6 char(3),
    Kyakusitu1 char(3),
    Kyakusitu2 char(3),
    Kyakusitu3 char(3),
    Kyakusitu4 char(3),
    RaceCount char(3),
    PRIMARY KEY (KettoNum)
);

CREATE TABLE UMA_RACE
(
    RecordSpec char(2),
    DataKubun char(1),
    MakeDate char(8),
    Year char(4),
    MonthDay char(4),
    JyoCD char(2),
    Kaiji char(2),
    Nichiji char(2),
    RaceNum char(2),
    Wakuban char(1),
    Umaban char(2),
    KettoNum char(10),
    Bamei char(36),
    UmaKigoCD char(2),
    SexCD char(1),
    HinsyuCD char(1),
    KeiroCD char(2),
    Barei char(2),
    TozaiCD char(1),
    ChokyosiCode char(5),
    ChokyosiRyakusyo char(8),
    BanusiCode char(6),
    BanusiName char(64),
    Fukusyoku char(60),
    reserved1 char(60),
    Futan char(3),
    FutanBefore char(3),
    Blinker char(1),
    reserved2 char(1),
    KisyuCode char(5),
    KisyuCodeBefore char(5),
    KisyuRyakusyo char(8),
    KisyuRyakusyoBefore char(8),
    MinaraiCD char(1),
    MinaraiCDBefore char(1),
    BaTaijyu char(3),
    ZogenFugo char(1),
    ZogenSa char(3),
    IJyoCD char(1),
    NyusenJyuni char(2),
    KakuteiJyuni char(2),
    DochakuKubun char(1),
    DochakuTosu char(1),
    Time char(4),
    ChakusaCD char(3),
    ChakusaCDP char(3),
    ChakusaCDPP char(3),
    Jyuni1c char(2),
    Jyuni2c char(2),
    Jyuni3c char(2),
    Jyuni4c char(2),
    Odds char(4),
    Ninki char(2),
    Honsyokin char(8),
    Fukasyokin char(8),
    reserved3 char(3),
    reserved4 char(3),
    HaronTimeL4 char(3),
    HaronTimeL3 char(3),
    KettoNum1 char(10),
    Bamei1 char(36),
    KettoNum2 char(10),
    Bamei2 char(36),
    KettoNum3 char(10),
    Bamei3 char(36),
    TimeDiff char(4),
    RecordUpKubun char(1),
    DMKubun char(1),
    DMTime char(5),
    DMGosaP char(4),
    DMGosaM char(4),
    DMJyuni char(2),
    KyakusituKubun char(1),
    PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban, KettoNum)
);

